name: Run tools

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    # Allow triggering manually on other branches.

permissions:
  contents: read
  pull-requests: read

# This is for non-version-specific checks.
jobs:
  run-tools:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: |
          test-requirements.txt
          tool-requirements.txt
          pyproject.toml
    - name: Read project dependencies
      run: |
        python .github/workflows/read_deps.py
    - name: Install dependencies
      id: install_deps
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -r pyproject-deps.txt -r tool-requirements.txt
    - name: Lint with Ruff
      run: |
        ruff check src/srctools/
      # Override regular check, to run all tools even if one fails.
      if: ${{(success() || failure()) && steps.install_deps.outcome == "success"}}
    # Test both ends of the version, to catch version changes.
    - name: MyPy - Python 3.7
      run: |
        mypy --version
        mypy --python-version 3.7 src/srctools/ type_tests/
      if: ${{(success() || failure()) && steps.install_deps.outcome == "success"}}
    - name: MyPy - Python 3.11
      run: |
        mypy --python-version 3.11 src/srctools/ type_tests/
      if: ${{(success() || failure()) && steps.install_deps.outcome == "success"}}
