name: Run tools

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    # Allow triggering manually on other branches.

# This is for non-version-specific checks.
jobs:
  run-tools:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -r test-requirements.txt
        python -m pip install mypy==0.980 flake8
    - name: Build package
      run: |
        python -m pip install --editable .
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    # Test both ends of the version, to catch version changes.
    - name: MyPy version 3.7
      run: |
        mypy --python-version 3.7 src/srctools/
    - name: MyPy version 3.10
      run: |
        mypy --python-version 3.10 src/srctools/
